name: wallet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  barcode: ^2.2.6
  barcode_widget: ^2.0.4
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  intl: ^0.19.0
  page_transition: ^2.1.0
  sqflite: ^2.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
