name: wallet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  barcode: ^2.2.6
  barcode_widget: ^2.0.4
  bloc: ^8.1.2
  crypt: ^4.3.1
  dcdg: ^4.1.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bcrypt: ^1.0.8
  flutter_bloc: ^8.1.3
  flutter_logs: ^2.1.11
  flutter_screen_lock: ^9.0.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  logger: ^2.2.0
  mqtt_client: ^10.2.0
  page_transition: ^2.1.0
  pointycastle: ^3.7.4
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
